# Generated by Django 6.0.7 on 2026-07-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Geneva Business', max_length=255)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(help_text='Star rating from 1 to 5')),
                ('comment', models.TextField(help_text="The customer's original review text")),
                ('detected_language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=5)),
                ('ai_draft_reply', models.TextField(blank=True, help_text='AI generated draft response', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted to Google')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
