# Generated by Django 6.0.7 on 2026-07-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='brand_tone',
            field=models.CharField(choices=[('friendly', '😊 Friendly & Warm (Best for Cafes, Restaurants)'), ('professional', '💼 Professional & Formal (Best for Clinics, Law/Consulting)'), ('casual', '⚡ Casual & Playful (Best for Fitness, Trendy Shops)')], default='friendly', max_length=20),
        ),
    ]
