# Generated by Django 6.0.7 on 2026-08-01 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_businessprofile_brand_tone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Table 1 or Front Counter', max_length=100)),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, unique=True)),
                ('google_review_url', models.URLField(help_text='Destination for happy customers (4-5 stars)')),
                ('private_feedback_url', models.URLField(blank=True, help_text='Internal feedback form for unhappy customers (1-3 stars)', null=True)),
                ('fallback_url', models.URLField(help_text='Default URL if no specific rule matches')),
                ('total_scans', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
