# Generated by Django 6.0.7 on 2026-08-01 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_smartqrcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Cafe De Paris', max_length=255)),
                ('location', models.CharField(default='Geneva', help_text='City or neighborhood', max_length=255)),
                ('avg_rating', models.FloatField(default=4.0, help_text='Rating out of 5.0')),
                ('total_reviews', models.IntegerField(default=0, help_text='Total review count')),
                ('google_maps_url', models.URLField(blank=True, help_text='Optional link to Google Maps entry', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
