# Generated by Django 6.0.7 on 2026-08-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_competitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted to Google'), ('flagged', 'Flagged - Needs Manual Review')], default='pending', max_length=20),
        ),
    ]
