# Generated by Django 6.0.7 on 2026-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
