# Generated by Django 6.0.7 on 2026-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_businessprofile_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='custom_prompt',
            field=models.TextField(blank=True, help_text='Extra facts/rules fed into the AI prompt (e.g. parking info, signature dishes).', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='signature',
            field=models.CharField(blank=True, help_text='Appended to the end of every generated reply.', max_length=255, null=True),
        ),
    ]
