# Generated by Django 6.0.7 on 2026-08-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_businessprofile_custom_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_review_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
