# Generated by Django 6.0.7 on 2026-08-09 05:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_businessprofile_tripadvisor_url_review_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='tripadvisor_url',
        ),
        migrations.RemoveField(
            model_name='review',
            name='source',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='webhook_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
