# Generated by Django 6.0.7 on 2026-08-09 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_remove_businessprofile_tripadvisor_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='webhook_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
