# Generated by Django 6.0.7 on 2026-08-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_businessprofile_webhook_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='tripadvisor_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('tripadvisor', 'TripAdvisor'), ('webhook', 'Custom Webhook')], default='google', max_length=20),
        ),
    ]
