# Generated by Django 6.0.7 on 2026-08-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_businessprofile_tripadvisor_url_review_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted to Google'), ('flagged', 'Flagged - Needs Manual Review'), ('generation_failed', 'AI Generation Failed')], default='pending', max_length=20),
        ),
    ]
