# Generated by Django 6.0.7 on 2026-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='google_business_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google_business_location_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google_business_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='google_business_token',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='last_manual_post_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
