# Generated by Django 6.0.7 on 2026-08-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_businessprofile_google_business_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='creativity_level',
            field=models.CharField(choices=[('low', 'Precise & Consistent'), ('medium', 'Balanced'), ('high', 'Creative & Varied')], default='medium', help_text="Controls how much wording varies between similar replies (maps to the model's temperature).", max_length=10),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='response_length',
            field=models.CharField(choices=[('short', 'Concise (1-2 sentences)'), ('medium', 'Balanced (2-4 sentences)'), ('long', 'Detailed (4-6 sentences)')], default='medium', help_text='Controls how many sentences the AI writes per reply.', max_length=10),
        ),
    ]
