# Generated by Django 6.0.7 on 2026-08-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_businessprofile_creativity_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='blacklisted_words',
            field=models.TextField(blank=True, help_text='Comma-separated words/phrases the AI must never use in a reply (e.g. competitor names, sensitive terms).', null=True),
        ),
    ]
