# Generated by Django 6.0.7 on 2026-08-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_businessprofile_blacklisted_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_likely_spam',
            field=models.BooleanField(default=False, help_text='Flagged by AI as likely fake, bot-generated, or irrelevant content.'),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='AI-classified emotional tone of the review, independent of star rating.', max_length=10, null=True),
        ),
    ]
