# Generated by Django 6.0.7 on 2026-08-16 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_review_is_likely_spam_review_sentiment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='last_training_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='learned_patterns',
            field=models.TextField(blank=True, help_text='AI-generated summary of how this owner edits drafts, auto-injected into future prompts.', null=True),
        ),
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_draft', models.TextField()),
                ('final_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='reviews.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
