# Generated by Django 6.0.7 on 2026-08-16 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_businessprofile_last_training_run_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('settings_updated', 'Updated AI Settings'), ('review_approved', 'Approved a Review Reply'), ('team_invite_sent', 'Sent Team Invite'), ('team_invite_revoked', 'Revoked Team Invite')], max_length=30)),
                ('detail', models.CharField(blank=True, help_text='Short human-readable summary, e.g. review name or setting changed.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
