# Generated by Django 6.0.7 on 2026-08-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_hours_end',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='business_hours_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False, help_text='Hold negative-review alert emails outside business hours and send them at the next opening time instead.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='timezone_name',
            field=models.CharField(default='Europe/Zurich', help_text='IANA timezone, e.g. Europe/Zurich, Europe/Paris.', max_length=50),
        ),
    ]
