# Generated by Django 6.0.7 on 2026-08-20 20:57

import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_businessprofile_business_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartqrcode',
            name='slug',
            field=models.SlugField(default=reviews.models.generate_short_slug, editable=False, unique=True),
        ),
    ]
