# Generated by Django 6.0.7 on 2026-08-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_alter_smartqrcode_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], default='other', max_length=10)),
                ('resulted_in_rating', models.IntegerField(blank=True, help_text='Star tapped on the Smart Rating Gate, if any.', null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='reviews.smartqrcode')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
    ]
