# Generated by Django 6.0.7 on 2026-08-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_qrscanevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='Embedded in the center of your QR codes when set.', null=True, upload_to='business_logos/'),
        ),
    ]
