# Generated by Django 6.0.7 on 2026-08-22 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_businessprofile_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='linked_user',
            field=models.OneToOneField(blank=True, help_text="Set automatically once someone signs up with this invite's email.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
