# Generated by Django 6.0.7 on 2026-08-24 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='smartqrcode',
            name='active_hours_enabled',
            field=models.BooleanField(default=False, help_text='If on, this code only routes customers during the hours below — outside that window it shows a closed notice instead.'),
        ),
        migrations.AddField(
            model_name='smartqrcode',
            name='active_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartqrcode',
            name='active_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartqrcode',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Teammate responsible for this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_qr_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smartqrcode',
            name='expires_at',
            field=models.DateField(blank=True, help_text='After this date, the code stops routing customers — useful for time-limited promotions.', null=True),
        ),
    ]
