# Generated by Django 6.0.7 on 2026-08-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0030_synclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='last_auto_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='sync_frequency',
            field=models.CharField(choices=[('manual', 'Manual only (click Sync Reviews yourself)'), ('daily', 'Daily'), ('hourly', 'Hourly'), ('realtime', 'Real-time (checks every 5 min)')], default='manual', help_text='How often to automatically pull new Google reviews in the background.', max_length=10),
        ),
    ]
