# Generated by Django 6.0.7 on 2026-08-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0031_businessprofile_last_auto_sync_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited')], max_length=15),
        ),
    ]
