# Generated by Django 6.0.7 on 2026-08-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0032_alter_synclog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='trustpilot_waitlist_joined_at',
            field=models.DateTimeField(blank=True, help_text='Set when the owner asks to be notified once Trustpilot integration opens up.', null=True),
        ),
    ]
