# Generated by Django 6.0.7 on 2026-08-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0033_businessprofile_trustpilot_waitlist_joined_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_simulated',
            field=models.BooleanField(default=False, help_text='True if created via Review Simulator, not a real synced review.'),
        ),
    ]
