# Generated by Django 6.0.7 on 2026-08-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0034_review_is_simulated'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(default=50, help_text='Max AI generations (drafts + regenerations) allowed per day for this business. Protects against runaway Gemini API costs.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='ai_generations_today',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='ai_last_generation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
