# Generated by Django 6.0.7 on 2026-09-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0036_accesscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('premium', 'Premium'), ('founding_partner', 'Founding Partner')], default='starter', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
