# Generated by Django 6.0.7 on 2026-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0037_businessprofile_plan_businessprofile_plan_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='detected_language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English'), ('de', 'German'), ('it', 'Italian'), ('gsw', 'Swiss German (Schwiizerdütsch)')], default='fr', max_length=5),
        ),
    ]
