# Generated by Django 6.0.7 on 2026-09-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0038_alter_review_detected_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='geo_seo_enabled',
            field=models.BooleanField(default=True, help_text="Pro feature toggle for Local SEO Keyword Reinforcement (GEO/AEO). Placeholder for future plan-based gating — currently on for everyone since billing isn't wired up yet."),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text="Comma-separated local SEO/GEO phrases (e.g. 'terrace near Lake Geneva, authentic fondue Old Town'). The AI weaves one in ONLY when a review naturally supports it — never forced.", null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='first_response_at',
            field=models.DateTimeField(blank=True, help_text='Set the moment a reply first became approved or posted — used to compute average response time. Never overwritten after first set, even if the reply is later edited or regenerated.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='seo_keyword_used',
            field=models.CharField(blank=True, help_text='The local SEO phrase (if any) the AI naturally worked into this reply. Blank means none was used — expected for most replies.', max_length=255, null=True),
        ),
    ]
