# Generated by Django 6.0.7 on 2026-09-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0039_businessprofile_geo_seo_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='action_link_enabled',
            field=models.BooleanField(default=False, help_text="Pro feature: invite happy reviewers to a booking page, event, or offer. Off by default — this is promotional, so it's an explicit opt-in unlike SEO keywords."),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='action_link_label',
            field=models.CharField(blank=True, help_text="What the link is, in plain words the AI can reference naturally, e.g. 'our autumn wine tasting event', 'table reservations', 'our online store'.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='action_link_min_rating',
            field=models.PositiveSmallIntegerField(default=4, help_text='Only offered on reviews with this star rating or higher — never shown to unhappy customers.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='action_link_url',
            field=models.URLField(blank=True, help_text='Destination link — booking page, event page, online store, etc.', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='action_link_shown',
            field=models.BooleanField(default=False, help_text='True if a promotional action link (booking, event, store) was appended to this reply.'),
        ),
    ]
