# Generated by Django 6.0.7 on 2026-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0040_businessprofile_action_link_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='subscription_status',
            field=models.CharField(blank=True, help_text='Mirrors Stripe: trialing, active, past_due, canceled, unpaid, etc.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
