# Generated by Django 6.0.7 on 2026-09-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_businessprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='requested_email',
            field=models.EmailField(blank=True, help_text='Email that requested this code', max_length=254),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Sent'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
