# Generated by Django 6.0.7 on 2026-10-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0042_accesscode_requested_email_accesscode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Review ID from the data provider, used to avoid duplicates.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_url',
            field=models.URLField(blank=True, help_text='Direct Google Maps link to this specific review.', max_length=1000, null=True),
        ),
    ]
