# Generated by Django 6.0.7 on 2026-10-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0043_review_external_id_review_review_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='sync_frequency',
            field=models.CharField(choices=[('manual', 'Manual only (click Sync Reviews yourself)'), ('daily', 'Daily'), ('hourly', 'Hourly')], default='manual', help_text='How often to automatically pull new Google reviews in the background.', max_length=10),
        ),
    ]
