# Generated by Django 6.0.7 on 2026-10-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0044_alter_businessprofile_sync_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='sync_frequency',
            field=models.CharField(choices=[('manual', 'Manual only (click Sync Reviews yourself)'), ('daily', 'Daily')], default='manual', help_text='How often to automatically pull new Google reviews in the background.', max_length=10),
        ),
    ]
